### ISSUE TITLE
[1.12] Crash on Startup

### ISSUE THREAD

**Issue by kenijey** [crazysnailboy/EnchantingTable#1]
[crash-2017-06-15_14.30.38-client.txt](https://github.com/crazysnailboy/EnchantingTable/files/1077432/crash-2017-06-15_14.30.38-client.txt)
used forge 2327, dunno why :(

**Comment by crazysnailboy** [comment]
It's because of changes in Forge since I released the 1.12 version of the mod. I used Forge 2322, and then 2323 broke it a couple of hours later :|

I'll get an update out to resolve it as soon as I can - thanks for letting me know :)

**Comment by crazysnailboy** [comment]
Version [1.1.2-beta1](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table/files/2434571/download) resolves this.

**Comment by kenijey** [comment]
thanks.
