### ISSUE TITLE
Incompatibility with Dimensional Doors

### ISSUE THREAD

**Issue by Dalethium** [crazysnailboy/EnchantingTable#10]
Hey! So there is a startup crash with the mod Dimensional Doors! I have reported this to their repo [here](https://github.com/DimensionalDevelopment/DimDoors/issues/52)

[Crash Report](https://pastebin.com/fPsmh9gg)

I love this mod and I use it all the time! Hopefully this issue can be fixed!

**Comment by Runemoro** [comment]
By the way, this was also reported here:
 - https://github.com/crazysnailboy/EnchantingTable/issues/8
 - https://github.com/crazysnailboy/EnchantingTable/issues/7
 - https://github.com/crazysnailboy/EnchantingTable/issues/6

**Comment by crazysnailboy** [comment]
I've published v1.1.3 which includes a fix for this, kindly provided by Runemoro. Please let me know if you get any more problems :)
