### ISSUE TITLE
[1.10.2] Crash with other mods

### ISSUE THREAD

**Issue by BrisingrAerowing** [crazysnailboy/EnchantingTable#6]
[Crash Log](https://gist.github.com/BrisingrAerowing/77d26740d71ae5a025698266f681095e)

I think [this line](https://github.com/crazysnailboy/EnchantingTable/blob/1.10/src/main/java/net/crazysnailboy/mods/enchantingtable/capability/CapabilityHandler.java#L84) is the issue, the instanceof probably needs to check against EntityPlayer, not EntityLivingBase. Attaching capabilities to some mobs will cause them to crash (those mods should be able to handle capabilities being attached without crashing, but some don't code in the guards for that).

**Comment by Robijnvogel** [comment]
Might I kindly ask what safeguards we **could** code in for this?

**Comment by Sunconure11** [comment]
@Robijnvogel I'd advise seeing if you can take over the mod from here, the dev of this hasn't been active in a while, and the license should allow it.

**Comment by crazysnailboy** [comment]
Thanks for the feedback guys, and apologies that I've not been active in a while. I've published v1.1.3 which includes BrisingrAerowing's suggested change from EntityLivingBase to EntityPlayer, as well as Runemoro's PR moving the registration from Init to PreInit.

Please let me know if you get any more problems.
