### ISSUE TITLE
Crash when trying to create entity during mod initialization causes incompatibility with DimDoors

### ISSUE THREAD

**Issue by Runemoro** [crazysnailboy/EnchantingTable#7]
In our mod [DimDoors](https://github.com/DimensionalDevelopment/DimDoors), we're creating an entity during mod initialization to save its NBT.

That causes EnchantingTable to fail to load the CapabilityHandler.Provider class: https://hastebin.com/raw/memabiyavo

**Comment by BrisingrAerowing** [comment]
This appears to be similar to the issue I reported for 1.10.2 (same exception type and stack trace). Likely the same cause.

**Comment by crazysnailboy** [comment]
Apologies for the delayed response, and many thanks for the PR :) I've published v1.1.3 which includes your change, hopefully this will resolve the issues people are having.

Thanks again - please let me know if you get any more problems.
