### ISSUE TITLE
incompatibility with exotic birds

### ISSUE THREAD

**Issue by xkforce** [crazysnailboy/EnchantingTable#8]
https://pastebin.com/beL682vi

discussion w/ exotic birds dev about the issue:
https://minecraft.curseforge.com/projects/exotic-birds/issues/1

**Comment by BrisingrAerowing** [comment]
Technically a duplicate of #6 (which has more info on why this occurs as well).

**Comment by crazysnailboy** [comment]
I've published v1.1.3 which includes a fix for this, kindly provided by Runemoro. Please let me know if you have any more issues :)
